name: manager
description: A new Flutter project.



publish_to: "none" 


version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"


dependencies:
  analyzer: ^6.2.0
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.0
  hive_flutter: ^1.1.0
  riverpod_annotation: ^2.3.3
 

dev_dependencies:
  
  
  
  
  
  build_runner: ^2.4.7
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7




flutter_icons:
  android: true
  image_path: "assests/logo.jpg"
  
flutter:  
  uses-material-design: true
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
